name: Release repos
on:
  workflow_call:
    inputs:
      TAG:
        description: 'Tag to be published'
        required: true
        type: string
      ONLY_TAG:
        description: "Only Tag"
        required: false
        type: string
        default: false
      BRANCH:
        description: 'Branch name'
        required: true
        type: string
      LATEST:
        description: 'Latest release'
        required: false
        type: string
        default: true
      BODY:
        description: 'Release body message'
        required: true
        default: 'Changes in this Release'
        type: string
      PRE_RELEASE:
        description: 'Pre-release? True/False'
        required: false
        default: false
        type: string
      DRAFT:
        description: 'Draft? True/False'
        required: false
        default: false
        type: string
    secrets:
      SLACK_WEBHOOK_URL:
        required: true

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create a release with a tag
        run: |
          PRE_RELEASE=''
          if [[ ${{ inputs.PRE_RELEASE }} == 'true ]]; then
            PRE_RELEASE='--prerelease'
          fi
          DRAFT=''
          if [[ ${{ inputs.DRAFT }} == 'true' ]]; then
            DRAFT='--draft'
          fi
          LATEST='--latest'
          if [[ ${{ inputs.LATEST }} == 'false' ]]; then
            LATEST='--latest=false'
          fi
          ONLY_TAG=''
          if [[ ${{ inputs.ONLY_TAG }} == 'true' ]]; then
            git tag ${{ inputs.TAG }}
            git push origin ${{ inputs.TAG }}
          else
            gh release create ${{ inputs.TAG }} $LATEST --target=${{ inputs.BRANCH }}   --title "${{ inputs.TAG }}" --notes "${{ inputs.BODY }}" $PRE_RELEASE $DRAFT
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,author,commit,workflow,job # selectable (default: repo,message)
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: failure() # Pick up events even if the job fails or is canceled.