name: Release from CSV
on:
  workflow_call:
    inputs:
      CSV_FILE:
        description: path of csv file
        required: false
        type: string
        default: ./release/Repo_release/repolist.csv
    secrets:
      SLACK_WEBHOOK_URL:
        required: true
      TOKEN:
        required: true

jobs:
  create-releases-from-csv:
    name: Create Releases from CSV
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install yq
        run: sudo snap install yq
      - name: Create Releases from CSV
        run: |
          while IFS=, read -r REPO TAG ONLY_TAG BRANCH LATEST BODY PRE_RELEASE DRAFT; do
            if [[ "$REPO" == \"REPO\" ]]; then
              echo "CSV header line ignoring";
              continue;
            fi
           # Output key-value pairs
            echo "REPO: $REPO"
            echo "TAG: $TAG"
            echo "ONLY_TAG: $ONLY_TAG"
            echo "BRANCH: $BRANCH"
            echo "LATEST: $LATEST"
            echo "BODY: $BODY"
            echo "PRE_RELEASE: $PRE_RELEASE"
            echo "DRAFT: $DRAFT"
            echo "-----------------------------"
          done < "$CSV_FILE"
      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,author,commit,workflow,job # selectable (default: repo,message)
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: failure() # Pick up events even if the job fails or is canceled.
